### ISSUE TITLE
Some sort of auth for hosting on a public URL

### ISSUE THREAD

**Issue by fizzyduck** [isaaceindhoven/velocita-proxy#2]
Do you have any thoughts on how authentication could be approached? I am considering putting velocita on a public facing URL so that cloud builds can take easy advantage of it.

Possibly creating a Docker image that includes some of the [vouch-proxy](https://github.com/vouch/vouch-proxy) setup?

Just throwing this out there at the moment for discussion.

**Comment by GMTA** [comment]
Currently, Velocita itself does not ask for authentication. The easiest way to add authentication right now, would be to put a reverse proxy in front of Velocita that does require authentication.

In the future, we might allow TLS client certificate authentication or basic authentication to take place.

**Comment by GMTA** [comment]
Composer-Velocita should also support sending credentials if we want to fully implement this.

**Comment by GMTA** [comment]
@fizzyduck I've added basic authentication support to both the Velocita plugin and proxy. How to get it working:

* Use `composer-velocita` version `3.2.0` or newer
* Use the `velocita-proxy` Docker image version `3.1.0` or newer
* Follow the instructions [in the README](https://github.com/isaaceindhoven/velocita-proxy/blob/master/proxy/README.md#enabling-basic-authentication) on setting up basic authentication

Note that you should only do this if the access to Velocita goes through HTTPS, since basic authentication is pretty much the same as plaintext authentication.

Let me know if this helps you!

**Comment by GMTA** [comment]
Closing ticket - @fizzyduck let me know if you have any additional remarks/feedback.
