### ISSUE TITLE
Proxy headers to origin

### ISSUE THREAD

**Issue by p24-max** [isaaceindhoven/velocita-proxy#4]
Some private repositories (eg. composer.amasty.com) also require that the User-Agent (eg. `Composer/1.9`) is sent to the origin in order to grant access. Otherwise the request is rejected with 401.

So the http headers need to be proxied to the origin as well.

**Comment by GMTA** [comment]
That's some top notch security measure if I've ever seen one. :clown_face: 

However, since Velocita is a caching proxy, we don't send request headers to the origin if the response is already cached. Additionally, I don't necessarily think it's a good idea to send along arbitrary headers from the original request.

My proposal would be to allow configuring the outgoing `User-Agent` on a per-mirror basis. Would that work for you @p24-max ?

**Comment by p24-max** [comment]
> That's some top notch security measure if I've ever seen one. 🤡

I read in the nginx manual that all headers are proxy'd with proxy_pass if not overwritten:
> To prevent a header field from being passed to the proxied server, set it to an empty string as follows

(Source: https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/#passing-request-headers)

And this is the case for User-Agent: https://github.com/isaaceindhoven/velocita-proxy/blob/master/proxy/templates/proxy.conf.erb#L141

--
> My proposal would be to allow configuring the outgoing User-Agent on a per-mirror basis. Would that work for you @p24-max ?

Yeah that would work and would fit my need 🤩

**Comment by GMTA** [comment]
Please check out release v3.5.0 which contains a new `MIRROR_*_USER_AGENT` environment variable that you can use. Let me know if this fixes your issue!

**Comment by p24-max** [comment]
@GMTA works perfectly! Thank you :)
